version: '3.8'

services:
  wow-website:
    build: .
    container_name: sde-wow-website
    restart: always
    ports:
      - "11564:3000"
    networks:
      - wow-network
    env_file:
      - .env

networks:
  wow-network:
    external: true
