services:
  sde-wow-website:
    build: .
    container_name: sde-wow-website
    restart: always
    ports:
      - "11564:3000"
    networks:
      - wow-network
    env_file:
      - .env

networks:
  wow-network:
    name: wow-network
    external: true